export const baseRules = {
  "skapxd/class-properties-require-readonly": "error",
  "skapxd/max-public-methods": "error",
  "skapxd/no-accessors": "error",
  "skapxd/no-ad-hoc-ok-result": "error",
  "skapxd/no-deep-relative-imports": "error",
  "skapxd/no-default-export": "error",
  "skapxd/no-else": "error",
  "skapxd/no-emoji": "error",
  "skapxd/no-nested-if": "error",
  "skapxd/no-runtime-state-guard": "error",
  "skapxd/no-promise-chain": "error",
  "skapxd/no-try-catch": "error",
  "skapxd/one-root-function-per-file": "error",
  "skapxd/prefer-tagged-union-state": "error",
  "skapxd/requires-strict-tsconfig": "error",
  "skapxd/prefer-ts-pattern": "error",
  "skapxd/result-error-requires-cause": "error",
  "skapxd/result-error-requires-handling": "error",
};
